import React from "react";
import "./styles/myReset.css";
import "./styles/root-layout-style.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**Body required in root*/
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="page">
        {children}
        <div className="footer">
          <p>THIS FOOTER TEXT INHARITANCE IN ALL PAGES AND ROUTES</p>
        </div>
      </body>
    </html>
  );
}
